
CREATE TABLE `PERSONA` (
	`ID_PERSONA` INT(11) NOT NULL AUTO_INCREMENT,
	`COD_PAIS_NACIONALIDAD` VARCHAR(3) NOT NULL,
	`COD_TIPO_DOCUMENTO` VARCHAR(3) NOT NULL,
	`COD_SEXO` VARCHAR(1) NOT NULL,
	`FECHA_NACIMIENTO` DATE NOT NULL,
	`NOMBRE` VARCHAR(60) NOT NULL,
	`APELLIDO` VARCHAR(25) NOT NULL,
	`NUMERO_DOCUMENTO` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_PERSONA`)
);

CREATE TABLE `SEXO` (
  `COD_SEXO` VARCHAR(1) NOT NULL,
  `DESC_SEXO` varchar(50) NOT NULL,
   PRIMARY KEY (`COD_SEXO`)
);

CREATE TABLE `TIPO_DOCUMENTO` (
  `COD_TIPO_DOCUMENTO` VARCHAR(3) NOT NULL,
  `DESC_TIPO_DOCUMENTO` varchar(50) NOT NULL,
  PRIMARY KEY (`COD_TIPO_DOCUMENTO`)
);

CREATE TABLE `PAIS` (
  `COD_PAIS` VARCHAR(3) NOT NULL,
  `DESC_PAIS` varchar(50) NOT NULL,
  PRIMARY KEY (`COD_PAIS`)
);

INSERT INTO SEXO(COD_SEXO, DESC_SEXO) VALUES ("M", "MASCULINO");
INSERT INTO SEXO(COD_SEXO, DESC_SEXO) VALUES ("F", "FEMENINO");

INSERT INTO TIPO_DOCUMENTO(COD_TIPO_DOCUMENTO, DESC_TIPO_DOCUMENTO) VALUES ("DNI", "DOCUMENTO NACIONAL DE IDENTIDAD");
INSERT INTO TIPO_DOCUMENTO(COD_TIPO_DOCUMENTO, DESC_TIPO_DOCUMENTO) VALUES ("CDI", "CEDULA DE IDENTIDAD");

INSERT INTO PAIS(COD_PAIS, DESC_PAIS) VALUES ("AR", "ARGENTINA");
INSERT INTO PAIS(COD_PAIS, DESC_PAIS) VALUES ("BRA", "BRASIL");






